flowchart LR
    author[Content author] --> content[content/maps/event_XX]
    content --> dialog_src[dialog_pre.gml / portraits / bg PNG]
    content --> event_json[rewards.json / battleset.json]
    dialog_src --> import[Import to GameMaker assets]
    event_json --> datafiles[datafiles/ Included Files]
    import --> scripts[SCR_DialogExample_* scripts]
    import --> sprites[sprites/map art]
    scripts --> marker[OBJ_Map1_Marker Create]
    sprites --> marker
    datafiles --> engine[World map + battle engine]
